name: Pull Requests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: shayancanonical/observability/.github/workflows/rock-pull-request.yaml@feature/configure_rock_pull_request
