name: Release changed rocks to OCI Factory

on:
  push:
    branches:
      - main
    paths:
      - "temporal-server/**"
      - "!temporal-server/upgrader/**"
      - "temporal-ui/**"

  workflow_dispatch:
    inputs:
      rock-directory:
        description: "Rock directory to release, e.g. temporal-ui/2.52.1"
        required: true
        type: string

      dry-run:
        description: "Generate the OCI Factory change without pushing or opening a PR"
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  pull-requests: read

jobs:
  changed-rocks:
    if: ${{ github.event_name == 'push' }}
    uses: canonical/workflows-team/.github/workflows/get_modified_directories_by_marker.yaml@test-oci-workflow
    with:
      marker: rockcraft.yaml
      base-ref: ${{ github.event.before }}

  release:
    name: Release ${{ matrix.rock-directory }}
    needs: changed-rocks
    if: >-
      ${{
        github.event_name == 'push' &&
        needs.changed-rocks.outputs.paths != '[]' &&
        needs.changed-rocks.outputs.paths != ''
      }}

    strategy:
      fail-fast: false
      matrix:
        rock-directory: ${{ fromJSON(needs.changed-rocks.outputs.paths) }}

    uses: canonical/workflows-team/.github/workflows/rock-release-oci-factory.yaml@test-oci-workflow

    with:
      source-repository: canonical/temporal-rocks
      source-ref: ${{ github.sha }}
      rock-directory: ${{ matrix.rock-directory }}
      rock-support: minor
      risk-track: stable
      dry-run: false

    secrets:
      WF_CHARMERS_BOT_TOKEN: ${{ secrets.WF_CHARMERS_BOT_TOKEN }}
      WF_CHARMERS_BOT_GPG_PRIVATE: ${{ secrets.WF_CHARMERS_BOT_GPG_PRIVATE }}
      WF_CHARMERS_BOT_GPG_PASSPHRASE: ${{ secrets.WF_CHARMERS_BOT_GPG_PASSPHRASE }}

  manual-release:
    name: Release ${{ inputs.rock-directory }}
    if: ${{ github.event_name == 'workflow_dispatch' }}

    uses: canonical/workflows-team/.github/workflows/rock-release-oci-factory.yaml@main

    with:
      source-repository: canonical/temporal-rocks
      source-ref: ${{ github.sha }}
      rock-directory: ${{ inputs.rock-directory }}
      rock-support: minor
      risk-track: stable
      dry-run: ${{ inputs.dry-run }}

    secrets:
      WF_CHARMERS_BOT_TOKEN: ${{ secrets.WF_CHARMERS_BOT_TOKEN }}
      WF_CHARMERS_BOT_GPG_PRIVATE: ${{ secrets.WF_CHARMERS_BOT_GPG_PRIVATE }}
      WF_CHARMERS_BOT_GPG_PASSPHRASE: ${{ secrets.WF_CHARMERS_BOT_GPG_PASSPHRASE }}